name: Sync ImmortalWRT 24.10.0 Releases

on:
  workflow_dispatch: # Возможность вручную запустить Action

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    outputs:
      release_exists: ${{ steps.check_release.outputs.release_exists }}
      release_tag: ${{ steps.get_release.outputs.release_tag }} 
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get the latest release from ImmortalWRT 24.10.0
        id: get_release
        run: |
          # Указываем релиз 24.10.0 напрямую, если это фиксированная версия
          RELEASE_TAG="v24.10.0"
          RELEASE_NAME="ImmortalWRT 24.10.0"
          echo "::set-output name=release_tag::$RELEASE_TAG"
          echo "::set-output name=release_name::$RELEASE_NAME"

      - name: Check if release exists in your repo
        id: check_release
        run: |
          RELEASE_EXISTS=$(curl -s https://api.github.com/repos/Slava-Shchipunov/awg-openwrt/releases/tags/${{ steps.get_release.outputs.release_tag }} | jq -r .tag_name)
          if [ "$RELEASE_EXISTS" == "null" ]; then
            echo "::set-output name=release_exists::false"
          else
            echo "::set-output name=release_exists::true"
          fi

      - name: Create release in your repo
        if: steps.check_release.outputs.release_exists == 'false'
        run: |
          ART=" 
          \`\`\`
            _______                     ________        __
           |       |.-----.-----.-----.|  |  |  |.----.|  |_
           |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
           |_______||   __|_____|__|__||________||__|  |____|
                    |__| A M N E Z I A   W I R E G U A R D
          -----------------------------------------------------
          ImmortalWRT 24.10.0
          -----------------------------------------------------
          \`\`\`"

          curl -X POST https://api.github.com/repos/Slava-Shchipunov/awg-openwrt/releases \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg tag "${{ steps.get_release.outputs.release_tag }}" \
                    --arg name "Build amnezia wg for all devices with ImmortalWRT 24.10.0" \
                    --arg body "$ART" \
                    '{ tag_name: $tag, name: $name, body: $body }')"
  
  run-build:
    runs-on: ubuntu-latest
    needs: sync-releases
    if: needs.sync-releases.outputs.release_exists == 'false'
    uses: Slava-Shchipunov/awg-openwrt/.github/workflows/build-module.yml@master
    with:
      tag_name: ${{ needs.sync-releases.outputs.release_tag }}
